spring.application.name=demo-rabbintmq

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.queue=nestor_queue
spring.json.queue=nestor_json_queue
spring.exchange=nestor_exchange
spring.json.exchange=nestor_json_exchange
spring.routing.key=nestor_routing_key
spring.routing.json.key=nestor_routing_json_key